# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRxSyeG6UBmGypZP2uN1ETdTxs6gvkG6
"""



"""# **Semana 07 - 03**"""

#Temas:
#  1.Números
#  2.Variables
#  3.Manejo de Cadenas
#  4.Ingreso de Datos por el teclado
#  5.Operadores

#3.Manejo de Cadenas
cadena = "Universidad Nacional Tecnologica de Lima Sur"
cadena

#Universidad Nacional Tecnologicade Lima Sur
#012345.....

cadena[5]

#Tambien considera los espacios
cadena[11]

#Tambien se puede mostrar accediendo de manera inversa
cadena[-5]

#Para mostrar una subcadena [desde,hasta un antes]
#En java era substring()
cadena[3:8]

#Para saber el tamaño de una cadema utilizamos len()
#Incluye espacios en blanco
len(cadena)

#Para mostrar una cadena en mayuscula utilizamos upper()
cadena.upper()

#Para mostrar una cadena en minuscula utilizamos lower()
cadena.lower()

#Gmerar ima ñosta a partir de una cadena, spli()
cadena.split()

#Genera una lista utilizando un criterio de seperacion a partir de una cadena .spli()
#En este caso vamos a generar una lista de toda la cadena,
#Utilizando como criterio de seperacion la letra A
cadena.split("a")

#Forma clasica, concatenar con +
nombre = "Flor Cerdam"
print("Buenas tardes" + nombre)

#Utilizando el .format()
nombre = "Pablo Levano"
edad = 10
print("Hola {} ya se que tienes {} años".format(nombre,edad))

#Dar formato a numeros con muchos decimales
resultado = 10/3
print("10/3 es = {} ".format(resultado))

print("10/3 es = {r:1.3f} ".format(r=resultado))

#Dar formato con F
#La funcion f, esta disponible desde la version 3.6
nombres = "Daniel levano"

edad = 8

print(f"buenosdias {nombres} , ya se que tienes {edad} años")

#Dar formato a numero a con muchos decimales con f
resultado = 10/3
print(f"10/3 es = {resultado}")



"""# **Semana 07 - 04**"""

#Temas:
#  1.Números
#  2.Variables
#  3.Manejo de Cadenas
#  4.Ingreso de Datos por el teclado
#  5.Operadores

#4.Ingreso de datos por el teclado
#Funcion input()
print("CUal es tu nombre")
nombre = input()
print("hola " + nombre)

#Cuando ingresa un valor por el teclado lo hace como cadena
print("numero 1: ")
numero1 = input()
print("numero 2: ")
numero2 = input()
numero3 = int(numero1) + int(numero2)
print(f"El resultado es {numero3}")



"""# **Semana 07 - 05**"""

#Temas:
#  1.Números
#  2.Variables
#  3.Manejo de Cadenas
#  4.Ingreso de Datos por el teclado
#  5.Operadores

#5.Operadores
#5.1. Operadores aritmeticos
#Se tiene: +,-,*,/,%,//

numero1 = 19
numero2 = 2
suma = numero1 + numero2
resta = numero1 - numero2
residuo = numero1 % numero2
cociente = numero1 // numero2
potencia = numero1 * numero2

print(suma,resta,residuo,cociente,potencia)

# 5.2 Operadores de asignación
#Se tiene: =, +=, -=, *=, /=, **=
numero = 5
numero = numero + 3 
print(numero)

# 5.2 Operadores de asignación
#Se tiene: =, +=, -=, *=, /=, **=
numero = 5
numero = numero + 3 
print(numero)

# La operación anterior también se puede expresar de la siguiente manera:
numero = 5 
numero +=3
print(numero)

# Lo mismo se puede hacer con todos los casos, incluso la potencia
# veamos otro ejemplo:
numero =5 
numero **= 2
print(numero)

# 5.3 Operadores de compración
# Se tiene: ==, !=, <, >, <=, >=,
#Ejemplo de igualdad ==
numero1 = 5 
numero2 = 2 
numero1 == numero2

# Con las cadenas funciona igual
nombre1 = "Juan"
nombre2 = "Juan"
nombre1 == nombre2

#5.4 operadores lógicos
# se tiene: and, or, not 
numero1=5 
numero2=6
numero3=7
numero4=8
numero1 < numero2

#El not invierte el resultado
not(numero1<numero2)

# También puedes utilizar parentesis para ordenar tu operación
(numero1 <numero2 and numero3<numero4) or (numero3>numero4)

# 5.5 Operadores de Pertenencia
#Se tiene: in, not in 
aula = ["Juan", "Daniel", "Ruben"]
alumno1= "Diego"
alumno2= "Juan"
# ¿Diego está en aula?
alumno1 in aula

# ¿Juan esta en aula?
alumno2 in aula

# ¿Diego no está en el aula?
alumno1 not in aula

# ¿Juan no está en aula? 
alumno2 not in aula

# 5.6 Operadores de identidad 
# Se tiene: is, is not

aula1 = ["Juan", "Daniel", "Ruben"]
aula2 = ["Juan", "Daniel", "Ruben"]
#A continuación vmaos a indicar que aula 3 va a 
#compartir el mismo objeto que aula1
aula3 = aula1;
# ¿aula3 comparte el mismo objeto que aula1?
aula3 is aula1

# aula3 comparte el mismo objheto que aula2
aula3 is aula2

# ¿Aula2 comparte el mismo objeto que aula1?
aula2 is aula1

aula1.append("Diego")
# Al imprimir los elemnetos de la lista aula1 se obsserva
print(aula1)
['Juan', 'Daniel', 'Ruben', 'Diego']
# Al imprimir los elementos de la lista aula3 se observa
print(aula3)
['Juan', 'Daniel', 'Ruben', 'Diego']
# Al imprimir los elementos de la lista aula2 se observa
print(aula2)