# -*- coding: utf-8 -*-
"""Semana07_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JS12OZ_QM2FlNLUsuEfQLNqKlgu8OCSX
"""

#Semana 07
#Edson Emanuel Alvarado Prieto

#Temas:
#  1.Números
#  2.Variables
#  3.Manejo de Cadenas
#  4.Ingreso de Datos por el teclado
#  5.Operadores

#2.Variables
#Siempre debe iniciar con una eltra o un guión abajo(Nunca un numero u otro simbolo)

edad = 41
edad

nombre = "Edson"
nombre

apellido = "Alvarado Prieto"
apellido

nombrecompleto = nombre + " " + apellido
nombrecompleto

#Para saber el tipo de variable usamos type()
numero = 50
type(numero)

type(nombre)

talla = 11.57
talla

#Para convertir un numero a cadena con str()
numero = 100
cadena = str(numero)
cadena

type(cadena)

#Para convertir una cadea en un entero utilizamos int()
cadena2 = "50"
numero2 = int(cadena2)
numero2

#Para convertir una cadena a un decimal usamos float()
cadena2 = "50"
numero2 = float(cadena2)
numero2

type(numero2)

